format = """
[](#394260)\
$os\
[](bg:#769ff0 fg:#394260)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
$git_state\
[](bg:#769ff0 fg:#394260)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nim\
$rust\
$scala\
$rlang\
$aws\
$nodejs\
$gcloud\
$azure\
$quarto\
$lua\
$python\
[](fg:#769ff0 bg:#394260)\
$docker_context\
[](fg:#394260)\
$linebreak\
[󰑆 ](bold green)\ 
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below


# An alternative to the username module which displays a symbol that
# represents the current operating system
[character]
success_symbol = "[](bold green)"
error_symbol = "[󰜺](bold red)"
vimcmd_symbol = "[](bold green)"

[os]
style = "fg:#ff9e64 bg:#394260"
disabled = false                # Disabled by default

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[directory]
style = "fg:#394260 bg:#769ff0"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[aws]
symbol = "󰸏 "
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[azure]
symbol = " "
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'
[c]
symbol = " "
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "fg:#769ff0 bg:#394260"
format = '[ $symbol $context ]($style)'

[elixir]
symbol = " "
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = " "
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_state]
# disabled = true
style = "bg:#394260 fg:#ff9e64"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([[](bg:#394260 fg:#394260)$state($progress_current/$progress_total)[](bg:#394260 fg:#394260)]($style)\)'

[git_status]
# disabled = true
style = "bg:#394260 fg:#93ce6a"
stashed = " ${count}"
behind = "ﲔ ${count}"
ahead = "ﲗ ${count}"
diverged = " 李 ${ahead_count} ${behind_count}"
conflicted = "[ ${count}](fg:red bg:#394260)"
deleted = " [${count}](fg:red bg:#394260)"
renamed = " 﫦${count}"
modified = "[ 凜${count}](fg:#ff9e64 bg:#394260)"
staged = "  ${count}"
untracked = "[  ${count}](fg:#ff9e64 bg:#394260)"
format = "([[](bg:#394260 fg:#394260)$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind[](bg:#394260 fg:#394260)]($style))"

[golang]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[gcloud]
symbol = "󱇶"
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥"
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[rlang]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'

[quarto]
symbol = "󰬘"
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'


[lua]
symbol = ""
style = "fg:#394260 bg:#769ff0"
format = '[ $symbol ($version) ]($style)'
