format = """
$os\
$directory\
$git_branch\
$git_status\
$git_state\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nim\
$rust\
$scala\
$rlang\
$aws\
$nodejs\
$gcloud\
$azure\
$quarto\
$lua\
$python\
$docker_context\
$linebreak
$character\
"""

# Disable the blank line at the start of the prompt
add_newline = true

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below


# An alternative to the username module which displays a symbol that
# represents the current operating system
[character]
success_symbol = "[󰇘❯](bold #2ac3d3)"
error_symbol = "[󰇘❯](bold red)"
vimcmd_symbol = "[❮](bold #2ac3d3)"

[os]
style = "#f7768e"
disabled = false                # Disabled by default

[os.symbols]
Windows = "󰍲 "
Ubuntu = " "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
Arch = "󰣇 "
Artix = "󰣇 "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[directory]
style = "bold #2ac3d3"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"


[aws]
symbol = "󰸏 "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[azure]
symbol = " "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[c]
symbol = " "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[docker_context]
symbol = " "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[elixir]
symbol = " "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[elm]
symbol = " "
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[git_branch]
symbol = ""
format = '[on ]( #a9b1d6 )[[ $symbol $branch ]( bold #bb9af7)]($style)'

[git_state]
# disabled = true
style = " fg:#bb9af7"
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = " picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\($state($progress_current/$progress_total)($style)\)'

[git_status]
# disabled = true
style = "fg:#bb9af7"
stashed = " ${count} "
behind = "ﲔ ${count} "
ahead = "ﲗ ${count} "
diverged = "李${ahead_count} ${behind_count} "
conflicted = " ${count} "
deleted = "${count} "
renamed = "﫦${count} "
modified = " ${count} "
staged = " ${count} "
untracked = " ${count} "
format = "[($stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind)](fg:#bb9af7)($style)"

[golang]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[gcloud]
symbol = "󱇶"
style = "fg:#7aa2f7"
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[gradle]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[haskell]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[java]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[julia]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[nodejs]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[nim]
symbol = "󰆥"
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[python]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[rust]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[rlang]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[scala]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[quarto]
symbol = "󰬘"
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'

[lua]
symbol = ""
format = '[via]( bold #a9b1d6 )($style)[ $symbol ($version) ](fg:#7aa2f7)($style)'
